import { Geist_Mono, Urbanist } from "next/font/google";
import "./globals.css";
const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CacheLogic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.className} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
